//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominaturn.WebService.Core.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atencion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Atencion()
        {
            this.AvisoExtra = new HashSet<AvisoExtra>();
        }
    
        public long Id { get; set; }
        public Nullable<long> IdEquipoVentanilla { get; set; }
        public Nullable<long> IdUsuario { get; set; }
        public long IdTurno { get; set; }
        public long IdTramite { get; set; }
        public Nullable<byte> Calificacion { get; set; }
        public bool Atendido { get; set; }
        public bool Mostrado { get; set; }
        public long Numero { get; set; }
        public string IdentificadorCliente { get; set; }
        public System.DateTime FechaHora { get; set; }
    
        public virtual EquipoVentanilla EquipoVentanilla { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Turno Turno { get; set; }
        public virtual Tramite Tramite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvisoExtra> AvisoExtra { get; set; }
    }
}
