//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominaturn.WebService.Core.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipoVentanillaCategoriaTramite
    {
        public long Id { get; set; }
        public long IdCategoriaTramite { get; set; }
        public long IdEquipoVentanilla { get; set; }
    
        public virtual CategoriaTramite CategoriaTramite { get; set; }
        public virtual EquipoVentanilla EquipoVentanilla { get; set; }
    }
}
