//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominaturn.WebService.Core.DataAccess.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DominaturnEntities : DbContext
    {
        public DominaturnEntities()
            : base("name=DominaturnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Atencion> Atencion { get; set; }
        public virtual DbSet<AvisoExtra> AvisoExtra { get; set; }
        public virtual DbSet<CategoriaTramite> CategoriaTramite { get; set; }
        public virtual DbSet<EquipoCliente> EquipoCliente { get; set; }
        public virtual DbSet<EquipoVentanilla> EquipoVentanilla { get; set; }
        public virtual DbSet<EquipoVentanillaCategoriaTramite> EquipoVentanillaCategoriaTramite { get; set; }
        public virtual DbSet<Noticia> Noticia { get; set; }
        public virtual DbSet<Requisito> Requisito { get; set; }
        public virtual DbSet<Tramite> Tramite { get; set; }
        public virtual DbSet<TramiteRequisito> TramiteRequisito { get; set; }
        public virtual DbSet<Turno> Turno { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
