//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominaturn.WebService.Core.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticia
    {
        public long Id { get; set; }
        public string Titulo { get; set; }
        public byte[] ColorTitulo { get; set; }
        public string Cuerpo { get; set; }
        public byte[] ColorCuerpo { get; set; }
        public System.DateTime FechaNoticia { get; set; }
        public System.DateTime FechaFin { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    }
}
