//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominaturn.WebService.Core.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TramiteRequisito
    {
        public long Id { get; set; }
        public long IdTramite { get; set; }
        public long IdRequisito { get; set; }
    
        public virtual Requisito Requisito { get; set; }
        public virtual Tramite Tramite { get; set; }
    }
}
